### PR TITLE
Update MAME 2000.opt: Added mame2000-audio

### PR DESCRIPTION
**Pull request by nummacway**

### CODE REVIEW

**Comment by tzubertowski** [comment]
Does this have any negative impact on the performance by any chance @nummacway ? Eg. I'm being suggested by pico8 performance with/without audio

**Comment by nummacway** [comment]
How is _disabling_ audio supposed to have negative impact on the performance?

**Comment by tzubertowski** [comment]
I'll be closing this PR, there's no PR description, no indication of the intent of change, no will to answer basic questions either.

**Comment by nummacway** [comment]
This was a question. Because I don't understand your concern as the _opposite_ of what you suggested is the case in pico8, and I'm not even changing the _default_ behaviour.

There is a clear description: "Update MAME 2000.opt: Added mame2000-audio"

I believed the intent of this repo was to make .opt files match the cores' _actual_ options. This wasn't the case before, so I changed it. Obviously I'm not understanding this repo correctly.

**Comment by tzubertowski** [comment]
> I believed the intent of this repo was to make .opt files match the cores' _actual_ options. This wasn't the case before, so I changed it. Obviously I'm not understanding this repo correctly.

You are understanding it correctly. 

I am just not merging in a change that the author of is not willing to answer a simple question by doing the smallest of smoketests to answer the question, instead them deciding to be snappy and thus waste the time.

**Comment by nummacway** [comment]
Needless to say, I checked m2k source if there is any _chance_ that setting the _default_ setting might change anything. If present, it's read to a longbool, depending on whether it is `"enabled"` or anything else. So I can _safely_ exclude any negative impact of the default setting.

I tested three things with the setting _disabled_:
* Does it work? Yes.
* Does it affect performance in `mslug4fd`? Didn't notice anything. But that's for this specific `neogeo` ROM (that isn't even supported by stock `m2k`).
* Does it prevent `REGION_SOUND1` from being allocated, so you have more space for the CROM (so you can load e.g. `mslugx`)? No it doesn't.

Does my change help anyone if there is no clear possitive impact of the non-default setting? Probably not. Are there other settings that have no impact? Yes, many.

So I guess you tested _every single_ setting in these opt files with tons of different ROMs. I would like to thank you for that hard work. I'm sorry I couldn't do that. :(

**Pull request closed without merging**
